### ISSUE TITLE
Improve component with extra registers for multiple device types

### ISSUE THREAD

**Issue by htvekov** [cfeenstra1024/kamstrup-multical-hardware#1]
Hi' @cfeenstra1024

Still waiting for the ESPHome PR to be merged before testing 🙂
I'm currently using ESPHome with my own 'tweaked' version of @cenobitedk Kamstrup custom component. Both for my district heating meter (Multical 602) as well as my water meter (flowIQ 2200).

I would suggest that you add the High Resolution register(s) to your component as well. For the x03 meter series it's a straight forward process. For the x02 series it's a bit more complicated as the HiRes register is a delta value. I've also added a calculated yearly cooling average sensor. Very useful in countries where the utility companies enforce 'penalty' tariffs for customers not cooling the water sufficiently. Reading the Unit Of Measurement from the actual device would also be a nice feature (not sure if you've already done that ?)

You could take a peek at my [fork](https://github.com/htvekov/esphome_multical402) if you're interested 🙂

**Comment by cfeenstra1024** [comment]
Hi @htvekov, 

Nice, you have different meters than I have. I only have a Multical 403. The component I created has native support for some of the most common registerers like 'Heat Energy' and 'Power'. However, you can add any number of registers yourself using the config file. See an example below that reads the high resolution register you've mentioned. I did not really want to add all possible registers in the component, but instead allow the (advanced) user to enter the register IDs themselves. 

Once the PR is merged, I am open to extending the list of sensors. But I'm really keen to have this component first in ESPHome, before I disturb reviewers with more commits ;)

I also thought about using the unit read from the device, and set that to the sensor. However, this seems not to be possible / allowed. After I'd created this, I received [some comments](https://github.com/esphome/esphome/pull/4200#pullrequestreview-1347750261) about that in the PR.

A documentation PR is also pending, explaining the config options. As long as this PR is open, you can check it out [here](https://deploy-preview-3513--esphome.netlify.app/components/sensor/kamstrup_kmp).

```yaml
uart:
  baud_rate: 1200
  stop_bits: 2
  tx_pin: GPIO15
  rx_pin: GPIO13

sensor:
  - platform: kamstrup_kmp
    heat_energy:
      name: 'Heat Energy'
    power:
      name: 'Heat Power'
    temp_diff:
      name: 'Heat Temperature Difference'
    flow:
      name: 'Heat Flow'
    temp1:
      name: 'Temp 1'
    temp2:
      name: 'Temp 2'
    volume:
      name: 'Volume'
    custom:
      - name: 'High Resolution Heat Energy'
        command: 0x010A
        unit_of_measurement: 'Wh'
      - name: 'Some other custom sensor (Power)'
        command: 0x0050
```
